#!/bin/bash

# 设置API密钥和城市ID
API_KEY="54a3fff476962fdb71589d741763719e"
CITY_ID="1799869"  # 贵阳城市ID

# 获取当前天气数据
CURRENT_WEATHER=$(curl -s "http://api.openweathermap.org/data/2.5/weather?id=$CITY_ID&appid=$API_KEY&units=metric")
CURRENT_TEMP=$(echo $CURRENT_WEATHER | jq -r '.main.temp')
CURRENT_CONDITION=$(echo $CURRENT_WEATHER | jq -r '.weather[0].description')

# 获取未来两天的天气预报数据
FORECAST=$(curl -s "http://api.openweathermap.org/data/2.5/forecast?id=$CITY_ID&appid=$API_KEY&units=metric")
TOMORROW_TEMP=$(echo $FORECAST | jq -r '.list[7].main.temp')
TOMORROW_CONDITION=$(echo $FORECAST | jq -r '.list[7].weather[0].description')
DAY_AFTER_TOMORROW_TEMP=$(echo $FORECAST | jq -r '.list[15].main.temp')
DAY_AFTER_TOMORROW_CONDITION=$(echo $FORECAST | jq -r '.list[15].weather[0].description')

# 构造消息内容
MESSAGE="贵阳现在的天气为：$CURRENT_TEMP℃，$CURRENT_CONDITION。明天的天气预报为：$TOMORROW_TEMP℃，$TOMORROW_CONDITION；后天的天气预报为：$DAY_AFTER_TOMORROW_TEMP℃，$DAY_AFTER_TOMORROW_CONDITION。"

# 发送消息到Matrix
curl -X POST -H "Content-Type: application/json" -d "{\"msgtype\": \"m.text\", \"body\": \"$MESSAGE\"}" "https://matrix.2046.eu.org/_matrix/client/r0/rooms/"\!qrCKXjlGOAUQAbBjUh:matrix.2046.eu.org"/send/m.room.message"
