name: Build/release docker images
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
    tags:
      - "*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lower case for ghcr
        id: ghcr_string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.event.repository.full_name }}

      - name: Set the image tag as output if not master branch
        if: github.ref_name != 'master'
        id: imageTag
        run: |
          IMAGE_TAG=$(echo ${{ steps.gitTag.outputs.tag }}); \
          echo "::set-output name=tag::$IMAGE_TAG"; \

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push latest images on master branch
        if: github.ref_name == 'master'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.ghcr_string.outputs.lowercase }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Build and push tagged images
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.ghcr_string.outputs.lowercase }}:${{ steps.imageTag.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
